routes/web.php
  Route::get('inspektoratambilagendasudahterlaksana', 'InspektoratAgendaController@ambil_agenda_sudah_terlaksanan');
  Route::get('inspektoratambilagendaprosespelaksanaan', 'InspektoratAgendaController@ambil_agenda_proses_pelaksanaan');
  Route::get('inspektoratambilagendabelumterlaksana', 'InspektoratAgendaController@ambil_agenda_belum_terlaksanan');

  Route::get('inspektorattampilperkegiatan/{id}', 'InspektoratAgendaController@tampil_per_kegiatan');
  Route::get('inspektorattampilperhari/{id}', 'InspektoratAgendaController@tampil_per_hari');

  Route::get('inspektorattampildetailkakpersatker/{id}', 'InspektoratKAKController@detailkakpersatker');

  Route::get('inspektoratdetailagenda/{id}', 'InspektoratKAKController@detailagenda');

  Route::get('inspektoratkakpdf/{id}','InspektoratKAKController@inspektoratkakpdf');
  // Route::get('inspektorattampilkegiatan/{id}', 'InspektoratAgendaController@tampil_kegiatan');
  //==========================================================================================

  //satker ==========================================================================================
  Route::resource('satkerindex','SatkerDashboardController');
  Route::resource('satkeragenda', 'SatkerAgendaController');
  Route::resource('satkerkak', 'SatkerKAKController');
  Route::put('satkerkakstatus/{id}', 'SatkerKAKController@ubahStatus');

  Route::get('satkerambilagendasudahterlaksana', 'SatkerAgendaController@ambil_agenda_sudah_terlaksanan');
  Route::get('satkerambilagendaprosespelaksanaan', 'SatkerAgendaController@ambil_agenda_proses_pelaksanaan');
  Route::get('satkerambilagendabelumterlaksana', 'SatkerAgendaController@ambil_agenda_belum_terlaksanan');

  Route::get('satkertampilperkegiatan/{id}', 'SatkerAgendaController@tampil_per_kegiatan');
  // Route::post('satkertampilperkegiatan', 'SatkerAgendaController@tampil_per_kegiatan');
  Route::get('satkertampilperhari/{id}', 'SatkerAgendaController@tampil_per_hari');

  Route::get('detailagenda/{id}', 'SatkerKAKController@detailagenda');

  Route::get('satkerkakpdf/{id}','SatkerKAKController@satkerkakpdf');

  Route::get('satkerdetailagendaubahstatusproses/{id}','SatkerAgendaController@detailagendaubahstatusproses');
  Route::get('satkerbuktiprogramsudahterlaksanan/{id}','SatkerAgendaController@buktiprogramsudahterlaksanan');
  //==========================================================================================

  //Validator bkaad==========================================================================================

  Route::resource('validatorbkaadagenda', 'ValidatorBkaadAgendaController');
  Route::resource('validatorbkaadindex', 'ValidatorBkaadDashboardController');
  Route::resource('validatorbkaadkak', 'ValidatorBkaadKAKController');

  Route::get('validatorbkaadambilagendasudahterlaksana', 'ValidatorBkaadAgendaController@ambil_agenda_sudah_terlaksanan');
  Route::get('validatorbkaadambilagendaprosespelaksanaan', 'ValidatorBkaadAgendaController@ambil_agenda_proses_pelaksanaan');
  Route::get('validatorbkaadambilagendabelumterlaksana', 'ValidatorBkaadAgendaController@ambil_agenda_belum_terlaksanan');

  Route::get('validatorbkaadtampilperkegiatan/{id}', 'ValidatorBkaadAgendaController@tampil_per_kegiatan');
  Route::get('validatorbkaadtampilperhari/{id}', 'ValidatorBkaadAgendaController@tampil_per_hari');

  Route::get('validatorbkaadtampildetailkakpersatker/{id}', 'ValidatorBkaadKAKController@detailkakpersatker');

  Route::get('validatorbkaaddetailagenda/{id}', 'ValidatorBkaadKAKController@detailagenda');

  Route::get('validatorbkaadupdatestatustersetujui/{id}', 'ValidatorBkaadKAKController@updatetersetujuipervalidator');
  Route::get('validatorbkaaddetailrevisi/{id}', 'ValidatorBkaadKAKController@detailrevisipervalidator');

  Route::get('validatorbkaadrevisi/{id}', 'ValidatorBkaadKAKController@revisi');
  Route::post('validatorbkaadtambahrevisi', 'ValidatorBkaadKAKController@tambahrevisi');

  Route::get('validatorbkaadupdaterevisibenar/{id}', 'ValidatorBkaadKAKController@updaterevisibenar');
  Route::get('validatorbkaadajukanrevisi/{id}', 'ValidatorBkaadKAKController@ajukanrevisi');
  // Route::get('inspektorattampilkegiatan/{id}', 'InspektoratAgendaController@tampil_kegiatan');
  //==========================================================================================

  //Validator bapeda==========================================================================================
  Route::resource('validatorbapedaagenda', 'ValidatorBapedaAgendaController');
  Route::resource('validatorbapedaindex', 'ValidatorBapedaDashboardController');
  Route::resource('validatorbapedakak', 'ValidatorBapedaKAKController');

  Route::get('validatorbapedaambilagendasudahterlaksana', 'ValidatorBapedaAgendaController@ambil_agenda_sudah_terlaksanan');
  Route::get('validatorbapedaambilagendaprosespelaksanaan', 'ValidatorBapedaAgendaController@ambil_agenda_proses_pelaksanaan');
  Route::get('validatorbapedaambilagendabelumterlaksana', 'ValidatorBapedaAgendaController@ambil_agenda_belum_terlaksanan');

  Route::get('validatorbapedatampilperkegiatan/{id}', 'ValidatorBapedaAgendaController@tampil_per_kegiatan');
  Route::get('validatorbapedatampilperhari/{id}', 'ValidatorBapedaAgendaController@tampil_per_hari');

  Route::get('validatorbapedatampildetailkakpersatker/{id}', 'ValidatorBapedaKAKController@detailkakpersatker');

  Route::get('validatorbapedadetailagenda/{id}', 'ValidatorBapedaKAKController@detailagenda');

  Route::get('validatorbapedaupdatestatustersetujui/{id}', 'ValidatorBapedaKAKController@updatetersetujuipervalidator');
  Route::get('validatorbapedadetailrevisi/{id}', 'ValidatorBapedaKAKController@detailrevisipervalidator');

  Route::get('validatorbapedarevisi/{id}', 'ValidatorBapedaKAKController@revisi');
  Route::post('validatorbapedatambahrevisi', 'ValidatorBapedaKAKController@tambahrevisi');

  Route::get('validatorbapedaupdaterevisibenar/{id}', 'ValidatorBapedaKAKController@updaterevisibenar');
  Route::get('validatorbapedaajukanrevisi/{id}', 'ValidatorBapedaKAKController@ajukanrevisi');
  // Route::get('validatorbapedaupdatestatusajukanrevisi/{id}', 'ValidatorBapedaKAKController@ajukanrevisi');
  //==========================================================================================

  //Validator inspektorat==========================================================================================
  Route::resource('validatorinspektoratagenda', 'ValidatorInspektoratAgendaController');
  Route::resource('validatorinspektoratindex', 'ValidatorInspektoratDashboardController');
  Route::resource('validatorinspektoratkak', 'ValidatorInspektoratKAKController');

  Route::get('validatorinspektoratambilagendasudahterlaksana', 'ValidatorInspektoratAgendaController@ambil_agenda_sudah_terlaksanan');
  Route::get('validatorinspektoratambilagendaprosespelaksanaan', 'ValidatorInspektoratAgendaController@ambil_agenda_proses_pelaksanaan');
  Route::get('validatorinspektoratambilagendabelumterlaksana', 'ValidatorInspektoratAgendaController@ambil_agenda_belum_terlaksanan');

  Route::get('validatorinspektorattampilperkegiatan/{id}', 'ValidatorInspektoratAgendaController@tampil_per_kegiatan');
  Route::get('validatorinspektorattampilperhari/{id}', 'ValidatorInspektoratAgendaController@tampil_per_hari');

  Route::get('validatorinspektorattampildetailkakpersatker/{id}', 'ValidatorInspektoratKAKController@detailkakpersatker');

  Route::get('validatorinspektoratdetailagenda/{id}', 'ValidatorInspektoratKAKController@detailagenda');

  Route::get('validatorinspektoratupdatestatustersetujui/{id}', 'ValidatorInspektoratKAKController@updatetersetujuipervalidator');
  Route::get('validatorinspektoratdetailrevisi/{id}', 'ValidatorInspektoratKAKController@detailrevisipervalidator');

  Route::get('validatorinspektoratrevisi/{id}', 'ValidatorInspektoratKAKController@revisi');
  Route::post('validatorinspektorattambahrevisi', 'ValidatorInspektoratKAKController@tambahrevisi');

  Route::get('validatorinspektoratupdaterevisibenar/{id}', 'ValidatorInspektoratKAKController@updaterevisibenar');
  Route::get('validatorinspektoratajukanrevisi/{id}', 'ValidatorInspektoratKAKController@ajukanrevisi');
  // Route::get('inspektorattampilkegiatan/{id}', 'InspektoratAgendaController@tampil_kegiatan');

  // Route::get('validatorinspektorattambahrevisi/{id}', 'ValidatorInspektoratKAKController@updaterevisipervalidator');
  //==========================================================================================


  //Operator ==========================================================================================
  Route::resource('operatorindex', 'OperatorDashboardController');


  Route::resource('operatordatasatker', 'OperatorDataSatkerController');
  Route::resource('operatordatapetugas','OperatorDataPetugasController');
  //==========================================================================================




// END INSPEKTORAT
  //Admin kategori Reguler==========================================================================================
  Route::resource('admin_kategori_reguler', 'AdminKategoriRegulerController');
  Route::get('datakategori_reguler', 'AdminKategoriRegulerController@listData')->name('datakategori_reguler');

  //Admin Produk Reguler==========================================================================================
  Route::resource('admin_produk_reguler', 'AdminProdukRegulerController');

  //Admin Users==========================================================================================
  Route::resource('admin_users', 'AdminPenggunaController');




});

Route::get('coba_pusher',function(){
    return view('coba_pusher');
});

Route::get('revisi',function(){
    return view('validatorinspektorat.revisi.index');
});

Route::get('firebase','FirebaseNotifikasiController@index');





Route::get('/masuk', function(){
	return view('login');
})->middleware('guest');

app/Pengguna.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Pengguna extends Model
{
  use Notifiable;

  protected $table = 'users';
  protected $primaryKey = 'iduser';
  protected $fillable = [
      'name', 'email', 'password',
  ];
  protected $hidden = [
      'password', 'remember_token',
  ];
}

resources/views/admin/pengguna/create.blade.php
<?php $hal = 'admin_users' ?>


@extends('layouts.admin.master')

@section('title', 'Tabel | Admin')

@section('css')
<link href="{{ asset('public/admin/lib/medium-editor/medium-editor.css') }}" rel="stylesheet">
<link href="{{ asset('public/admin/lib/medium-editor/default.css') }}" rel="stylesheet">
<link href="{{ asset('public/admin/lib/summernote/summernote-bs4.css') }}" rel="stylesheet">
<link href="{{ asset('public/admin/lib/select2/css/select2.min.css') }}" rel="stylesheet">
<link href="{{ asset('public/admin/lib/spectrum/spectrum.css') }}" rel="stylesheet">

@endsection

@section('content')
<!-- ##### MAIN PANEL ##### -->

<div class="kt-pagetitle">
  <h5>Form Users</h5>
</div><!-- kt-pagetitle -->

<div class="kt-pagebody">

  <div class="card pd-20 pd-sm-40">

    <div class="table-wrapper">
      <form class="form-horizontal tasi-form" action="{{ route('admin_users.store') }}" method="post" enctype="multipart/form-data">
                {{csrf_field()}}

                @if ($errors->any())
    							<div class="alert alert-danger"><ul>
    							@foreach($errors->all() as $error)
    							<li>{{ $error }}</li>
    							@endforeach
    							</ul></div>
    						@endif
                                  <div class="form-group">
                                      <label class="col-sm-2 col-sm-2 control-label">Nama</label>
                                      <div class="col-sm-10">
                                          <input type="text" class="form-control" name="nama" placeholder="Isikan Nama Pengguna">
                                      </div>
                                  </div>

                                  <div class="form-group">
                                      <label class="col-sm-2 col-sm-2 control-label">Email <span class="tx-danger">*</span></label>
                                      <div class="col-sm-10">
                                          <input type="email" class="form-control" name="email" placeholder="abcde@gmail.com">
                                      </div>
                                  </div>


                                  <div class="form-group">
                                      <label class="col-sm-4 col-sm-4 control-label">Password <span class="tx-danger">*</span> default (<span class="tx-danger"> cokelat12345</span>)</label>
                                      <div class="col-sm-10">
                                          <input type="password" readonly value="cokelat12345" class="form-control" name="password" placeholder="Isikan Nama Agenda">
                                      </div>
                                  </div>

                                  <div class="form-group">
                                      <label class="col-sm-2 col-sm-2 control-label"></label>
                                      <div class="col-sm-10">
                                          <button type="submit" class="btn btn-primary">Tambah</button>
                                      </div>
                                  </div>

                              </form>
    </div><!-- table-wrapper -->
  </div><!-- card -->






     </div><!-- kt-pagebody -->




@endsection


@section('js')
  <!-- <script src="{{ asset('admin/lib/jquery-ui/jquery-ui.js') }}"></script> -->
  <!-- <script src="{{ asset('public/admin/lib/highlightjs/highlight.pack.js') }}"></script>
  <script src="{{ asset('public/admin/lib/highlightjs/highlight.pack.js') }}"></script>
  <script src="{{ asset('public/admin/lib/datatables/jquery.dataTables.js') }}"></script>
  <script src="{{ asset('public/admin/lib/datatables-responsive/dataTables.responsive.js') }}"></script> -->

<script src="{{ asset('public/admin/lib/highlightjs/highlight.pack.js') }}"></script>
<script src="{{ asset('public/admin/lib/medium-editor/medium-editor.js') }}"></script>
<script src="{{ asset('public/admin/lib/summernote/summernote-bs4.min.js') }}"></script>
<script src="{{ asset('public/admin/lib/jquery-ui/jquery-ui.js') }}"></script>
<script src="{{ asset('public/admin/lib/highlightjs/highlight.pack.js') }}"></script>
<script src="{{ asset('public/admin/lib/select2/js/select2.min.js') }}"></script>
<script src="{{ asset('public/admin/lib/spectrum/spectrum.js') }}"></script>


@endsection

@section('script')



<script>
      $(function(){
        'use strict';

        // Inline editor
        var editor = new MediumEditor('.editable');

        // Summernote editor
        $('#summernote').summernote({
          height: 150,
          tooltip: false
        });

        'use strict';

        $('.select2').select2({
          minimumResultsForSearch: Infinity
        });

        // Select2 by showing the search
        $('.select2-show-search').select2({
          minimumResultsForSearch: ''
        });

        // Select2 with tagging support
        $('.select2-tag').select2({
          tags: true,
          tokenSeparators: [',', ' ']
        });


        // Datepicker
        $('.fc-datepicker').datepicker({
          showOtherMonths: true,
          selectOtherMonths: true
        });

      });
    </script>

@endsection

resources/views/admin/pengguna/edit.blade.php
<?php $hal = 'admin_users' ?>


@extends('layouts.admin.master')

@section('title', 'Tabel | Admin')

@section('css')
<link href="{{ asset('public/admin/lib/medium-editor/medium-editor.css') }}" rel="stylesheet">
<link href="{{ asset('public/admin/lib/medium-editor/default.css') }}" rel="stylesheet">
<link href="{{ asset('public/admin/lib/summernote/summernote-bs4.css') }}" rel="stylesheet">
<link href="{{ asset('public/admin/lib/select2/css/select2.min.css') }}" rel="stylesheet">
<link href="{{ asset('public/admin/lib/spectrum/spectrum.css') }}" rel="stylesheet">

@endsection

@section('content')
<!-- ##### MAIN PANEL ##### -->

<div class="kt-pagetitle">
  <h5>Produk Reguler</h5>
</div><!-- kt-pagetitle -->

<div class="kt-pagebody">

  <div class="card pd-20 pd-sm-40">

    <div class="table-wrapper">

      <form class="form-horizontal tasi-form" action="{{ route('admin_users.update',$pengguna->id) }}" method="post" enctype="multipart/form-data">
                {{csrf_field()}}
                {{ method_field('PUT') }}

                @if ($errors->any())
    							<div class="alert alert-danger"><ul>
    							@foreach($errors->all() as $error)
    							<li>{{ $error }}</li>
    							@endforeach
    							</ul></div>
    						@endif


                                  <div class="form-group">
                                      <label class="col-sm-2 col-sm-2 control-label">Nama Pengguna</label>
                                      <div class="col-sm-10">
                                          <input type="text" value="{{$pengguna->name}}" class="form-control" name="nama" placeholder="Isikan Nama Agenda">
                                      </div>
                                  </div>

                                  <div class="form-group">
                                      <label class="col-sm-2 col-sm-2 control-label">Email Baru<span class="tx-danger">*</span></label>
                                      <div class="col-sm-10">
                                          <input type="email" value="{{$pengguna->email}}"  class="form-control" name="email" placeholder="abcde@gmail.com">
                                      </div>
                                  </div>



                                  <div class="form-group">
                                    <label class="col-sm-2 col-sm-2 control-label">Password Baru<span class="tx-danger">*</span></label>
                                      <div class="col-sm-10">
                                          <input type="password" class="form-control" name="password" placeholder="Isikan Password Baru">
                                      </div>
                                  </div>




                <div class="form-group">
                                      <label class="col-sm-2 col-sm-2 control-label"></label>
                                      <div class="col-sm-10">
                                          <button type="submit" class="btn btn-primary">Update</button>
                                      </div>
                                  </div>

                              </form>

    </div><!-- table-wrapper -->
  </div><!-- card -->






     </div><!-- kt-pagebody -->




@endsection


@section('js')
  <!-- <script src="{{ asset('admin/lib/jquery-ui/jquery-ui.js') }}"></script> -->
  <!-- <script src="{{ asset('public/admin/lib/highlightjs/highlight.pack.js') }}"></script>
  <script src="{{ asset('public/admin/lib/highlightjs/highlight.pack.js') }}"></script>
  <script src="{{ asset('public/admin/lib/datatables/jquery.dataTables.js') }}"></script>
  <script src="{{ asset('public/admin/lib/datatables-responsive/dataTables.responsive.js') }}"></script> -->

<script src="{{ asset('public/admin/lib/highlightjs/highlight.pack.js') }}"></script>
<script src="{{ asset('public/admin/lib/medium-editor/medium-editor.js') }}"></script>
<script src="{{ asset('public/admin/lib/summernote/summernote-bs4.min.js') }}"></script>
<script src="{{ asset('public/admin/lib/jquery-ui/jquery-ui.js') }}"></script>
<script src="{{ asset('public/admin/lib/highlightjs/highlight.pack.js') }}"></script>
<script src="{{ asset('public/admin/lib/select2/js/select2.min.js') }}"></script>
<script src="{{ asset('public/admin/lib/spectrum/spectrum.js') }}"></script>


@endsection

@section('script')



<script>
      $(function(){
        'use strict';

        // Inline editor
        var editor = new MediumEditor('.editable');

        // Summernote editor
        $('#summernote').summernote({
          height: 150,
          tooltip: false
        });

        'use strict';

        $('.select2').select2({
          minimumResultsForSearch: Infinity
        });

        // Select2 by showing the search
        $('.select2-show-search').select2({
          minimumResultsForSearch: ''
        });

        // Select2 with tagging support
        $('.select2-tag').select2({
          tags: true,
          tokenSeparators: [',', ' ']
        });


        // Datepicker
        $('.fc-datepicker').datepicker({
          showOtherMonths: true,
          selectOtherMonths: true
        });

      });
    </script>

@endsection

resources/views/admin/pengguna/index.blade.php
<?php $hal = 'admin_users' ?>
<?php $sub = 0 ?>


@extends('layouts.admin.master')

@section('title', 'Tabel | Admin')

@section('content')
    <!-- ##### MAIN PANEL ##### -->

    <div class="kt-pagetitle">
      <h5>Data Users</h5>
    </div><!-- kt-pagetitle -->

    <div class="kt-pagebody">

      <div class="card pd-20 pd-sm-40">
        <a href="{{route('admin_users.create')}}" style="margin-bottom:20px; width:100px;" class="card-body-title"><button class="btn btn-primary">Tambah</button></a>

        <div class="table-wrapper">
          <table id="datatable1" class="table display responsive nowrap">
            <thead>
              <tr>
                  <th class="wd-15p">Nomor</th>
                <th class="wd-15p">Nama</th>
                <th class="wd-15p">Email</th>
                <th class="wd-20p">Password</th>
                <th class="wd-25p">Action</th>
              </tr>
            </thead>
            <tbody>

              <?php $no = 1 ?>
              @foreach($pengguna as $data)
              <tr>
                <td>{{$no}}</td>
                <td>{{$data->name}}</td>
                <td>{{$data->email}}</td>
                <td>****************</td>
                <td>

                  <form action="{{ route('admin_users.destroy', $data->id) }}" method="post">
											{{csrf_field()}}
											{{ method_field('DELETE') }}
                      <button <?php if($data->id==Auth::user()->id){echo "disabled='disabled'";}else{echo '';}?> class="btn btn-danger" onclick="return confirm('Are you sure?');" data-toggle="tooltip" data-placement="botttom" title="Hapus Data"><i class="icon ion-trash-b"></i></button >

                </form>
                </td>
              </tr>
                <?php $no++ ?>
              @endforeach


            </tbody>
          </table>
        </div><!-- table-wrapper -->
      </div><!-- card -->



@endsection


@section('js')
  <!-- <script src="{{ asset('admin/lib/jquery-ui/jquery-ui.js') }}"></script> -->
  <script src="{{ asset('public/admin/lib/highlightjs/highlight.pack.js') }}"></script>
  <script src="{{ asset('public/admin/lib/highlightjs/highlight.pack.js') }}"></script>
  <script src="{{ asset('public/admin/lib/datatables/jquery.dataTables.js') }}"></script>
  <script src="{{ asset('public/admin/lib/datatables-responsive/dataTables.responsive.js') }}"></script>

@endsection

@section('script')



<script>
   $(function(){
     'use strict';

     $('#datatable1').DataTable({
       responsive: true,
       language: {
         searchPlaceholder: 'Search...',
         sSearch: '',
         lengthMenu: '_MENU_ items/page',
       }
     });

     $('#datatable2').DataTable({
       bLengthChange: false,
       searching: false,
       responsive: true
     });

     // Select2
     $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });

   });
 </script>

@endsection